services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://backend:8000
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    networks:
      - sophon-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sophon:sophon@postgres:5432/sophon
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - sophon-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: sophon
      POSTGRES_PASSWORD: sophon
      POSTGRES_DB: sophon
    ports:
      - "5432:5432"
    volumes:
      - ./container/postgres:/var/lib/postgresql/data
    networks:
      - sophon-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - sophon-network

networks:
  sophon-network:
    driver: bridge

